version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: patients-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - JWT_SECRET=your-jwt-secret-key-change-in-production
      - FRONTEND_URL=http://localhost:3000
    volumes:
      - ./backend/database.sqlite:/app/database.sqlite
    networks:
      - patients-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: patients-frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:3001/api
    depends_on:
      - backend
    networks:
      - patients-network
    restart: unless-stopped

networks:
  patients-network:
    driver: bridge

volumes:
  db-data: 